services:
  dev-db:
    image: postgres:17.2-alpine
    container_name: om-dev-db
    environment:
      - POSTGRES_USER=om
      - POSTGRES_PASSWORD=om
      - POSTGRES_DB=om
    ports:
      - 5439:5432
