create type tp_sync_state AS ENUM ('Pending', 'Synced');
create cast	(varchar AS tp_sync_state) WITH INOUT AS IMPLICIT;

create type tp_account_state AS ENUM ('Temporary', 'Pending', 'Approved', 'Disabled');
create cast	(varchar AS tp_account_state) WITH INOUT AS IMPLICIT;

CREATE TABLE account (
	id int4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	created_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_updated_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"name" varchar(255) NULL,
	"uuid" uuid NOT NULL DEFAULT gen_random_uuid(),
	state tp_account_state NOT NULL DEFAULT 'Temporary'
);
CREATE UNIQUE INDEX idx_account_uuid ON account ("uuid");

CREATE TABLE image_cache (
	id int4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	created_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_updated_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	account_id int4 NOT NULL,
	image_name varchar(255) NULL,
	original_image_name varchar(255) NULL,
	original_image_height_px int4 NOT NULL,
	original_image_width_px int4 NOT NULL,
	CONSTRAINT fk_image_cache_account_id FOREIGN KEY (account_id) REFERENCES account(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX idx_image_cache_account_id_name ON image_cache (account_id, image_name);

create type tp_shop_state AS ENUM ('Pending', 'Approved', 'Disabled');
create cast	(varchar AS tp_shop_state) WITH INOUT AS IMPLICIT;

CREATE TABLE shop (
	id int4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	created_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_updated_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"name" varchar(255) NULL,
	slug varchar(50) NOT NULL,
	state tp_shop_state NOT NULL DEFAULT 'Pending',
	sync_state tp_sync_state NOT NULL DEFAULT 'Synced',
	account_id int4 NOT NULL,
	CONSTRAINT fk_shop_account_id FOREIGN KEY (account_id) REFERENCES account(id)
);
CREATE INDEX idx_shop_account_id ON shop (account_id);
CREATE INDEX idx_shop_sync_state ON shop (sync_state);
CREATE UNIQUE INDEX idx_shop_slug ON shop (slug);

CREATE TABLE shop_category (
	id int4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	created_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_updated_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	shop_id int4 NOT NULL,
	"name" varchar(255) NULL,
	visible boolean NOT NULL DEFAULT true,
	CONSTRAINT fk_shop_category_shop_id FOREIGN KEY (shop_id) REFERENCES shop(id)
);
CREATE UNIQUE INDEX idx_shop_category_shop ON shop_category (shop_id, "name");

CREATE TABLE shop_product (
	id int4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	created_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_updated_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	shop_id int4 NOT NULL,
	"name" varchar(255) NULL,
	visible boolean NOT NULL DEFAULT true,
	design_id int4 NOT NULL,
	category_id int4,
	creator_profit DECIMAL(8,2) NOT NULL DEFAULT 0,
	CONSTRAINT fk_shop_product_shop_id FOREIGN KEY (shop_id) REFERENCES shop(id),
	CONSTRAINT fk_shop_product_category_id FOREIGN KEY (category_id) REFERENCES shop_category(id)
);
CREATE UNIQUE INDEX idx_shop_product_shop ON shop_product (shop_id, "name");
CREATE INDEX idx_shop_product_category ON shop_product (shop_id, category_id);
CREATE UNIQUE INDEX idx_shop_product_design ON shop_product (design_id);

create type tp_user_state AS ENUM ('Temporary', 'Active', 'Disabled');
create cast	(varchar AS tp_user_state) WITH INOUT AS IMPLICIT;

CREATE TABLE usr (
	id int4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	created_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_updated_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"name" varchar(255) NULL,
	email varchar(255) NULL,
	oauth_subject varchar(10) NULL,
	sync_state tp_sync_state NOT NULL DEFAULT 'Synced',
	shipping_name varchar(100),
	shipping_street varchar(100),
	shipping_city varchar(100),
	shipping_zip INT,
	use_shipping_address boolean DEFAULT true,
	billing_name varchar(100),
	billing_street varchar(100),
	billing_city varchar(100),
	billing_zip INT
);
CREATE INDEX idx_usr_sync_state ON usr (sync_state);
CREATE UNIQUE INDEX idx_usr_oauth_subject ON usr (oauth_subject);
CREATE UNIQUE INDEX idx_usr_email ON usr (email);

CREATE TABLE creator (
	id int4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	created_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_updated_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	account_id int4 NOT NULL,
	user_id int4 NOT NULL,
	user_state tp_user_state NOT NULL DEFAULT 'Temporary',
	CONSTRAINT fk_creator_account_id FOREIGN KEY (account_id) REFERENCES account(id),
	CONSTRAINT fk_creator_user_id FOREIGN KEY (user_id) REFERENCES usr(id)
);
CREATE INDEX idx_creator_account_id ON creator (account_id);
CREATE INDEX idx_creator_user_state ON creator (user_state);
CREATE UNIQUE INDEX idx_creator_user_id ON creator (user_id);

CREATE TABLE shop_customer (
	id int4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	created_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_updated_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	shop_id int4 NOT NULL,
	user_id int4 NOT NULL,
	user_state tp_user_state NOT NULL DEFAULT 'Temporary',
	CONSTRAINT fk_customer_shop_id FOREIGN KEY (shop_id) REFERENCES shop(id),
	CONSTRAINT fk_creator_user_id FOREIGN KEY (user_id) REFERENCES usr(id)
);
CREATE INDEX idx_shop_customer_user_state ON shop_customer (user_state);
CREATE INDEX idx_shop_customer_user_id ON shop_customer (user_id);
CREATE UNIQUE INDEX idx_shop_customer_shop_id ON shop_customer (shop_id, user_id);

create type tp_order_state AS ENUM ('Cart', 'Pending', 'Processing', 'Finished', 'Cancelled', 'Returned', 'Refunded');
create cast	(varchar AS tp_order_state) WITH INOUT AS IMPLICIT;

CREATE TABLE shop_order (
	id int4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	created_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_updated_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	billing_date date NOT NULL DEFAULT CURRENT_TIMESTAMP,
	customer_id int4 NOT NULL,
	order_state tp_order_state NOT NULL DEFAULT 'Cart',
	total_price DECIMAL(9,2) NOT NULL DEFAULT 0,
	shipping_name varchar(100),
	shipping_street varchar(100),
	shipping_city varchar(100),
	shipping_zip INT,
	use_shipping_address boolean DEFAULT true,
	billing_name varchar(100),
	billing_street varchar(100),
	billing_city varchar(100),
	billing_zip INT,
	CONSTRAINT fk_shop_order_customer_id FOREIGN KEY (customer_id) REFERENCES shop_customer(id)
);
CREATE INDEX idx_shop_order_state ON shop_order (order_state);
CREATE INDEX idx_shop_order_customer_id ON shop_order (customer_id);

CREATE TABLE shop_order_item (
	id int4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	created_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_updated_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	order_id int4 NOT NULL,
	product_id int4 NOT NULL,
	unit_price DECIMAL(8,2) NOT NULL DEFAULT 0,
	unit_count INT NOT NULL DEFAULT 1,
	CONSTRAINT fk_shop_order_item_order_id FOREIGN KEY (order_id) REFERENCES shop_order(id)
);
CREATE UNIQUE INDEX idx_shop_order_item_order_id ON shop_order_item (order_id, product_id);

CREATE TABLE product_size (
	id int4 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	created_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_updated_on timestamptz(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"name" varchar(255) NOT NULL,
	product_id int4 NOT NULL,
	extra_price DECIMAL(8,2) NOT NULL DEFAULT 0,
	CONSTRAINT fk_product_size_product_id FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE
);
CREATE INDEX idx_product_size_product_id ON product_size (product_id);

ALTER TABLE product ADD COLUMN base_price DECIMAL(8,2) NOT NULL DEFAULT 0;
ALTER TABLE product_color ADD COLUMN extra_price DECIMAL(8,2) NOT NULL DEFAULT 0;
