ALTER TABLE shop ADD COLUMN background_color VARCHAR(20) NOT NULL DEFAULT '#ffffff';
ALTER TABLE shop ADD COLUMN foreground_color VARCHAR(20) NOT NULL DEFAULT '#000000';
ALTER TABLE shop ADD COLUMN link_color VARCHAR(20) NOT NULL DEFAULT '#0000ff';
ALTER TABLE shop ADD COLUMN font_family VARCHAR(255) NOT NULL DEFAULT 'Times New Roman, serif';
ALTER TABLE shop ADD COLUMN brand_bg_color VARCHAR(20) NOT NULL DEFAULT '#ff0000';
ALTER TABLE shop ADD COLUMN brand_fg_color VARCHAR(20) NOT NULL DEFAULT '#ffffff';
ALTER TABLE shop ADD COLUMN brand_image VARCHAR(255);
ALTER TABLE shop ADD COLUMN brand_show_name BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE shop ADD COLUMN brand_font_family VARCHAR(255) NOT NULL DEFAULT 'Arial, sans-serif';
