SELECT MAX(id) + 1 FROM product;

ALTER TABLE product ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (START WITH 7);

ALTER TABLE design ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE design_file ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;

SELECT MAX(id) + 1 FROM print_preview;

ALTER TABLE print_preview ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (START WITH 13);

SELECT MAX(id) + 1 FROM print_preview_zone;

ALTER TABLE print_preview_zone ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (START WITH 13);


SELECT MAX(id) + 1 FROM print_type;

ALTER TABLE print_type ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (START WITH 14);


SELECT MAX(id) + 1 FROM print_zone;

ALTER TABLE print_zone ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (START WITH 13);

SELECT MAX(id) + 1 FROM product_color;

ALTER TABLE product_color ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (START WITH 7);
